### ISSUE TITLE
Open pr_io.zip?

### ISSUE THREAD

**Issue by Docdraconova** [KiameV/final-fantasy-pr-save-editor#1]
When I try to load one of my save files (I've tried with both FF 1 PR and FF 5 PR, with the same result), I get a message telling me to "open pr_io.zip" and that access is d(enied, I imagine, but it cuts off there).  I'm not using any non-English text or any other mods, so I'm left a bit lost...

**Comment by KiameV** [comment]
Run the application as admin and see if that resolves the issue.

What's happening is the editor is downloading a decrypt program and the extract is failing probably due to folder privileges

**Comment by Docdraconova** [comment]
Same result, unfortunately.  I've even tried changing folder privileges for both the save file location and the folder I have the editor in, and I'm still getting the same "failed to load file" message.

**Comment by Docdraconova** [comment]
I've found that I can get 0.3.1 to work, so I tried a work-around someone mentioned on Steam - that is, putting the 0.4.4 executable in the old folder with the "io" directory.  No luck there, as I still got the same error message.
