### ISSUE TITLE
FF3 editor replaces party members

### ISSUE THREAD

**Issue by MasterDriverRex** [KiameV/final-fantasy-pr-save-editor#2]
Whenever I try to use the FF3 editor, the 'Party' tab has a list of my four party members - except all four slots are filled with my first member, and when I save and load in-game, that turns out to be my fourth party member.

I try to set it correctly (No. 1, No. 2, No. 3, No. 4) and save and load in-game, and now my party consists of (No. 4, No. 2, No. 3, No. 4) - which means that the program is erroneously setting No. 4 instead of No. 1, and thus there's no way to actually set No. 1 using this.

Even when I ignore the Party tab, it still screws up my party - because of this, this tool is basically nonfunctional as I cannot edit anything else without fucking up my party. Please fix, if you're still around.

**Comment by KiameV** [comment]
Thanks for the reported issue. As I investigate please download v0.4.6 which I just released which will leave the party section of the save alone.

https://github.com/KiameV/final-fantasy-pr-save-editor/releases/tag/0.4.6

Coming back to this after a year and I'd like to make improvements to this application in general. I'll investigate this further.

Sorry I was not able to get to this sooner!

**Comment by KiameV** [comment]
Resolved with the re-write
