### ISSUE TITLE
FFV error after loading file

### ISSUE THREAD

**Issue by STRIEH** [KiameV/final-fantasy-pr-save-editor#3]
I downloaded this tool to try and edit the character names to the original Japanese. Starting the game in English then changing languages keeps the English names in menus but not in dialogue.

I tried running with admin and older versions. I tried changing the language back to English and making an English save game but the error remains the same. I am also using the Memoria mod.

> failed to load file: Traceback (most recent call last):
    File "pr_io.py", line 54, in <module>
    File "pr_io.py", line 22, in deobfuscateFile
FileNotFoundError: [Errno 2] No such file or directory: 'save file name'
[11984] Failed to execute script 'pr_io' due to unhandled excep

**Comment by KiameV** [comment]
Resolved with the re-write
