### ISSUE TITLE
FFII party broken

### ISSUE THREAD

**Issue by Whitsel** [KiameV/final-fantasy-pr-save-editor#4]
First off, thank you for your work on this.

I've encountered an issue with the party becoming broken upon editing a FFII save. By default, all members are set to Firion when the save is loaded in the save editor. Saving this will display an empty party in game, and it will fail to load.

When manually selecting the members, Firion, Maria, Guy, and Leon (leaving Leon disabled), it will still show Leon in the save selection screen in-game, although he will be missing in the game. For some reason, I've experienced this also causing some weird glitching where the character bounces around while moving in the overworld, and no random encounters seem to spawn.

I have yet to find a viable workaround although I am still experimenting in an attempt to narrow down the problem

**Comment by KiameV** [comment]
Thanks for the reported issue. As I investigate please download v0.4.6 which I just released which will leave the party section of the save alone.

https://github.com/KiameV/final-fantasy-pr-save-editor/releases/tag/0.4.6

Coming back to this after a year and I'd like to make improvements to this application in general. I'll investigate this further.

**Comment by KiameV** [comment]
Resolved with the re-write
