### ISSUE TITLE
FF4 Completely Broken

### ISSUE THREAD

**Issue by TheXpertXD** [KiameV/final-fantasy-pr-save-editor#5]
The game refuses to load any save when even the slightest change is made. This is because the party selection is only slotted to have 4 people, when the game is designed to have 5

**Comment by KiameV** [comment]
Thanks for the reported issue. As I investigate please download `v0.4.6` which I just released which will leave the party section of the save alone.

https://github.com/KiameV/final-fantasy-pr-save-editor/releases/tag/0.4.6

Coming back to this after a year and I'd like to make improvements to this application in general. I'll investigate this further.

**Comment by KiameV** [comment]
Resolved with the re-write
