### ISSUE TITLE
Unable to load FF6 pixel remaster saves

### ISSUE THREAD

**Issue by Question2** [KiameV/final-fantasy-pr-save-editor#6]
@KiameV : Just gives the following error when i try : 

![image](https://github.com/KiameV/final-fantasy-pr-save-editor/assets/1191378/651f9c95-3cbc-4080-a22d-1573c0198c70)

**Comment by Question2** [comment]
Here are my saves just in case

[ff6 saves.zip](https://github.com/KiameV/final-fantasy-pr-save-editor/files/12430289/ff6.saves.zip)

**Comment by KiameV** [comment]
Resolved with the re-write
